version: '3.8'

services:
  # ----------------------------------------------------------------
  # 1. BANCO DE DADOS (Compartilhado)
  # ----------------------------------------------------------------
  db:
    image: postgres:15-alpine
    container_name: frota_postgres_db
    networks:
      - frota-net
    environment:
      - POSTGRES_USER=frota_next_user
      - POSTGRES_PASSWORD=frota_next_pass
      - POSTGRES_DB=frota_next_db
    volumes:
      - ./FrotaNext-Auth-main/src:/app/src
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U frota_next_user -d frota_next_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  # ----------------------------------------------------------------
  # 2. API DE AUTENTICAÇÃO (Auth Service)
  # ----------------------------------------------------------------
  auth-service:
    build: 
      context: ./FrotaNext-Auth-main
      dockerfile: Dockerfile
    container_name: frota_auth_service
    ports:
      - "8001:8000" 
    networks:
      - frota-net
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./FrotaNext-Auth-main/src:/app/src
    environment:
      - DATABASE_URL=postgresql+psycopg2://frota_next_user:frota_next_pass@db:5432/frota_next_db
      - SECRET_KEY=da59f57b85fc59b3c2aa2696f43e88c3c52b4e418a7c7274ba31be40cb117d85

  # ----------------------------------------------------------------
  # 3. BACKEND PRINCIPAL (Regras de Negócio)
  # ----------------------------------------------------------------
  backend:
    build: 
      context: ./FrotaNext-Backend-main
      dockerfile: Dockerfile
    container_name: frota_main_backend
    ports:
      - "8000:8000" 
    networks:
      - frota-net
    depends_on:
      db:
        condition: service_healthy
      auth-service:
        condition: service_started
    volumes:
      - ./FrotaNext-Backend-main/src:/app/src
      - ./reset-popula.py:/app/reset-popula.py
    environment:
      - DATABASE_URL=postgresql+psycopg2://frota_next_user:frota_next_pass@db:5432/frota_next_db
      - SECRET_KEY=da59f57b85fc59b3c2aa2696f43e88c3c52b4e418a7c7274ba31be40cb117d85
      - AUTH_API_INTERNAL_URL=http://auth-service:8000

  # ----------------------------------------------------------------
  # 4. FRONTEND (React)
  # ----------------------------------------------------------------
  frontend:
    build:
      context: ./FrotaNext-Frontend-main
      dockerfile: Dockerfile
    container_name: frota_frontend
    ports:
      - "3000:3000" 
    networks:
      - frota-net
    volumes:
      - ./FrotaNext-Frontend-main:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
      - VITE_AUTH_API_URL=http://localhost:8001

volumes:
  frota_pg_data:

networks:
  frota-net:
    driver: bridge
